### ISSUE TITLE
Bot randomly begins to duplicate payloads

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#103]
I'm unable to pinpoint the trigger, but it appears that the bot begins to duplicate itself randomly, sometimes straight after a reboot, sometimes after several weeks.

In the duplication, an identical payload is sent from the hangups client, so it would be possible to put in a hotfix that prevents the bot from acting on duplicate payloads.

**Comment by salaisuuxia** [comment]
it seems to happen most often after a loss of connection, especially with unstable plugins.

**Comment by nylonee** [comment]
There's also discussion happening in [wardellchandler/HangoutsBot](https://github.com/wardellchandler/HangoutsBot/issues/12) regarding the issue. Some interesting logs there too.

**Comment by xmikos** [comment]
It's fixed in my master branch, see this commit:
https://github.com/xmikos/hangupsbot/commit/59088d8d07b97403501dfd29b9e4c517a98ecf49

**Comment by xmikos** [comment]
That workaround by @endofline shouldn't be needed with this fix anymore.
