### ISSUE TITLE
lookup Plugin searches only in 100 rows

### ISSUE THREAD

**Issue by fantibaer** [nylonee/hangupsbot#104]
The Plugin lookup searches only in 100 rows in the Google spreadsheet (table)

How do I change it, to search across an entire table?

Thanks.

**Comment by nylonee** [comment]
I previously ran into this bug too, my solution was to publish the
spreadsheet (it doesn't go to public, it just means that there's now a URL
that links to an uneditable version of the sheet) and use that URL instead
to link to the sheet.

Let me know how that goes

**Comment by fantibaer** [comment]
Yes, thank you. :)

**Comment by FrNico** [comment]
@nylonee in case we don't want to make that spreadsheet public, is there any plan to still work on that plugin to use an auth cookie and still access more than 100 rows?
