### ISSUE TITLE
No straightforward way to permanently turn off bot 1-1's

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#116]
There needs to be a plugin or command to allow users to permanently turn off bot 1-1's. Currently several workarounds exist, including putting in a fake PushBullet API key to suppress the mentions, or turning on `/bot dnd` for 72 hours (the maximum that you can trigger `/bot dnd`), but shipping the bot without the functionality of allowing a complete opt-out is scary. **It could lead to frustrated end-users who report the bot for spam.**

EDIT: People are asking me "Why don't they just block the bot?" Users are unable to block the bot because then a message shows up on every chat that the bot is in saying "You have blocked somebody in this chat".

Thoughts on how we should implement this?

**Comment by endofline** [comment]
* use handler to suppress message sending for specific group ids. example: https://github.com/nylonee/hangupsbot/blob/staging/hangupsbot/plugins/_example_shutup.py
* modify https://github.com/nylonee/hangupsbot/blob/master/hangupsbot/hangupsbot.py#L315 to this to return a `False` if a specific user memory key is set - like "no-1to1", note that this may have to go as a core command into the bot if implemented in this way
