### ISSUE TITLE
[plugin] dynamically create simple question/answer hooks

### ISSUE THREAD

**Issue by neon-ninja** [nylonee/hangupsbot#118]
/bot when asked "question", answer "answer!"
/bot question?
bot: answer!

**Comment by neon-ninja** [comment]
Possibly auto add to autoreplies such that https://github.com/nylonee/hangupsbot/blob/master/hangupsbot/plugins/autoreply.py can handle the responding?

**Comment by neon-ninja** [comment]
This is possibly by saying:

/bot config append autoreplies [["question"],"answer!"]

**Comment by nylonee** [comment]
Added an admin command `/bot autoreply` that allows you to add and remove autoreplies (If you forget the format you can always use `/bot help autoreply` to see what the format of adding/removing is)
