### ISSUE TITLE
config doesn't support spaces in value

### ISSUE THREAD

**Issue by neon-ninja** [nylonee/hangupsbot#119]
https://github.com/nylonee/hangupsbot/blob/035bf0de6cd4a1c3a60f9a4228a5bad4b11438f6/hangupsbot/plugins/default.py#L144 doesn't work if [value] has spaces in it

**Comment by endofline** [comment]
this error can be repeated with the following command:
```
/bot config append autoreplies [["a question?"],"an answer!"]
```

exception thrown:
```
2015-04-04 18:29:34,262 - test - ERROR - CommandDispatcher.run: config
Traceback (most recent call last):
  File "/root/projects/nihalbot/hangupsbot/commands.py", line 39, in run
    yield from func(bot, event, *args, **kwds)
  File "/test/projects/nihalbot/hangupsbot/plugins/default.py", line 166, in config
    value = bot.config.get_by_path(config_args)
  File "/test/projects/nihalbot/hangupsbot/config.py", line 47, in get_by_path
    return functools.reduce(lambda d, k: d[k], keys_list, self)
  File "/test/projects/nihalbot/hangupsbot/config.py", line 47, in <lambda>
    return functools.reduce(lambda d, k: d[k], keys_list, self)
TypeError: list indices must be integers, not str
```

**Comment by endofline** [comment]
actually a good example of a bug with a non-trivial solution: the bugged command is split (by space) into:
```
autoreplies 
[["a 
question?"],"an 
answer!"]
```
with the first 3 tokens are consumed as the config path, with the 4th final token as the value

Since the config path is invalid, it raises the exception.

**Comment by endofline** [comment]
the fix also adds an enhancement to config.py, [allowing numerical paths for lists](https://github.com/nylonee/hangupsbot/blob/staging/hangupsbot/config.py#L47) retrieval from `config.json` e.g. `/bot config get hooks 0`, `/bot config get jsonrpc 3`, etc
