### ISSUE TITLE
plugins.subscribe doesn't work if plugins.dnd is disabled

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#124]
The current method that [subscribe.py](https://github.com/nylonee/hangupsbot/blob/master/hangupsbot/plugins/subscribe.py#L64) uses to check for DND will only work correctly if the DND plugin was loaded on start. Otherwise, subscribe will fail on [L64](https://github.com/nylonee/hangupsbot/blob/master/hangupsbot/plugins/subscribe.py#L64)

**Comment by endofline** [comment]
does call_shared throw an exception or actually return something?

**Comment by endofline** [comment]
don't delete this branch after staging merge, it also needs to be merged into **framework/2.4** branch
