### ISSUE TITLE
Simple memory polish

### ISSUE THREAD

**Issue by svbeon** [nylonee/hangupsbot#126]
Hi! Polishing the simple memory commands could be nice, in example
/bot rememberme
/bot rememberchat
/bot whatme
/bot whatchat
/bot forgetme
/bot forgetchat
This could be better to have as "standard" as they are shorter, easier to type and remember

**Comment by endofline** [comment]
these are actually intentionally long because they only serve as examples ;P on the other hand, no harm in shortening them either in later releases
