### ISSUE TITLE
simplytranslate plugin: accented word in a sentence gives no reply

### ISSUE THREAD

**Issue by FrNico** [nylonee/hangupsbot#133]
If an accented word (like in French language) is present in a sentence, no reply will be given.
J'aime la bière /english
will not reply "I like beer".

**Comment by nylonee** [comment]
Won't fix this until #137 is resolved and simplytranslate works again

**Comment by endofline** [comment]
after [updating my goslate to 1.4.0](https://github.com/nylonee/hangupsbot/issues/137#issuecomment-91392078), i have tried the test case `J'aime la bière /english` and it seems to be working, perhaps the goslate library broke around the same time this happened

**Comment by nylonee** [comment]
Works for me too. Closing this issue
