### ISSUE TITLE
lookup plugin: query from a user with accented name gives no reply

### ISSUE THREAD

**Issue by FrNico** [nylonee/hangupsbot#134]
If a user has an accented letter in his Google+ name, lookup plugin will not reply to him.
Example:
 - Grégory
 - Aurélien
etc...

**Comment by xmikos** [comment]
If it helps, I have had similar functionality already implemented in original HangupsBot from the beginning. And in latest refactoring I have moved it to _utils.py_ (it is now `unicode_to_ascii` function). See here: https://github.com/xmikos/hangupsbot/blob/master/hangupsbot/utils.py#L26

**Comment by endofline** [comment]
We need to update utils.py for 2.4 release as well, will look into merging
changes. Although I'm not quite sure why this would be the case for this
specific instance.

**Comment by xmikos** [comment]
It transliterates accented unicode characters, so e.g. `unicode_to_ascii('Český')` returns `'Cesky'`

**Comment by endofline** [comment]
not sure whether this is the fix but by 2.4, `/bot lookup grégory` and `/bot lookup gregory` should match the row `Grégory` and `Gregory` - accents will be ignored if they are present

**Comment by nylonee** [comment]
This works for me, fixed by 2.4. Closing this now
