### ISSUE TITLE
mention plugin: "-" character in composed names trigger no mention

### ISSUE THREAD

**Issue by FrNico** [nylonee/hangupsbot#135]
Composed name like Pierre-Yves, Jean-Nicolas, Pierre-Henri, etc... don't receive mention when adressed with their correct name.
Tried also with PierreYves instead of Pierre-Yves => no mention.

If you address them with first half (@Pierre) => will work (but not correct as Pierre != Pierre-Yves), and also, doesn't solve issue when in a room you have multiple users with composed name starting with same first half, for example, in a room you can have:
 - Jean-Christophe
 - Jean-Baptiste
etc...

**Comment by Deuteu** [comment]
"/bot mention Jean-Christophe" works but not as handy that "@Jean-Christophe"

**Comment by endofline** [comment]
@FrNico you can try hyphenated mentions again and see whether it works :)
