### ISSUE TITLE
translate plugins not working

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#137]
Currently it looks like the GoSlate library that is used for translating is having some issues and is not working. This is beyond control of the HangupsBot dev team, but for now **all plugins that rely on GoSlate ([simplytranslate](https://github.com/nylonee/hangupsbot/blob/eb83ea7084ffb381b0de0e56986f5d9fd3adcae6/hangupsbot/plugins/simplytranslate.py) and [syncrooms_autotranslate](https://github.com/nylonee/hangupsbot/blob/eb83ea7084ffb381b0de0e56986f5d9fd3adcae6/hangupsbot/plugins/syncrooms_autotranslate.py)) will not work until further notice.** 

Keep an eye on this issue for updates, or you can follow the [goslate bitbucket repo](https://bitbucket.org/zhuoqiang/goslate) for bleeding edge updates.

**Comment by endofline** [comment]
The bot should message if the exception being returned from the library is sufficiently specific to indicate the library/service is down. Can anybody log the exception and report back on it? That way we can catch it and output a relevant "service down" message.

**Comment by j16sdiz** [comment]
GoSlate is updated: https://pypi.python.org/pypi/goslate

**Comment by endofline** [comment]
thanks @j16sdiz - upgraded my own test copy `pip3 install goslate --upgrade`
