### ISSUE TITLE
bot messages published on a white background even in rooms with history off

### ISSUE THREAD

**Issue by FrNico** [nylonee/hangupsbot#138]
Not a serious issue, just cosmetic one, but seems bot always publish message in HTML with a white background, even in a hangout where history is off, and all other message are shown with a grey background.

Result in some questions from users, like "why bot can publish with history on" (which is not the case... obviously...).

**Comment by nylonee** [comment]
This was fixed a few days ago in the staging branch, since there wasn't an issue for it earlier I'm using this issue to track it until it gets pulled into master. Thanks =)
