### ISSUE TITLE
/bot echo should allow admin to send message to another room

### ISSUE THREAD

**Issue by FrNico** [nylonee/hangupsbot#140]
A modified version of "/bot echo" should allow admin to send message in another room using conv_id of the room or a shortname.
Example:
/bot send conv_id Hello world
Example with a defined nice name for a room, to make it more convenient:
/bot roomalias conv_id nicename
/bot send nicename Hello world

**Comment by xmikos** [comment]
You can look at `conv_send` command, https://github.com/xmikos/hangupsbot/blob/master/hangupsbot/commands/conversations.py#L63, it allows sending messages even to more conversations at once. Maybe you can port it to nylonee's HangupsBot
