### ISSUE TITLE
image upload / meme plugin issuse

### ISSUE THREAD

**Issue by NeoEGY** [nylonee/hangupsbot#144]
/bot meme test 
meme._retrieve(): getting http://memegenerator.net/memes/search?q=test
meme._retrieve(): getting http://memegenerator.net/John-Wall-Passes-Test
meme._retrieve(): getting http://memegenerator.net/instance/58885644
meme(): uploading 58885644.jpg from http://cdn.meme.am/instances/500x/58885644.jpg
send_html_to_conversation(): sending to UgwPzjlFkBaVv-8UFct4AaABAQ
'Client' object has no attribute 'upload_image'

also when posting and image link it recognize it but it can't upload it 

message: plugins.image_links._watch_image_link : coroutine
_watch_image_link(): getting https://i.imgur.com/Tt1kzvG.jpg
EXCEPTION in message: plugins.image_links._watch_image_link : coroutine

**Comment by nylonee** [comment]
@NeoEGY It seems to me like you don't have the latest hangups, can you pull the latest hangups version from [tdryer/hangups](https://github.com/tdryer/hangups), install that (try running `sudo python3 setup.py install` twice) and let me know if the problem persists?

**Comment by NeoEGY** [comment]
that fixed both plugings i usually just pull last changes without installing again
