### ISSUE TITLE
Import module errors

### ISSUE THREAD

**Issue by gurumadmat** [nylonee/hangupsbot#148]
Hi

I'm probably doing something wrong but I can't figure out what.

I'm getting these errors when starting hangupsbot:

http://pastebin.com/cXiFta9c

but when I try to install it using pip I get this:

Requirement already satisfied (use --upgrade to upgrade): wikipedia in /usr/local/lib/python3.3/dist-packages
Requirement already satisfied (use --upgrade to upgrade): goslate in /usr/local/lib/python3.3/dist-packages
Requirement already satisfied (use --upgrade to upgrade): wolframalpha in /usr/local/lib/python3.3/dist-packages
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/local/lib/python3.3/dist-packages/beautifulsoup4-4.3.2-py3.3.egg (from wikipedia)
Requirement already satisfied (use --upgrade to upgrade): requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.3/dist-packages/requests-2.3.0-py3.3.egg (from wikipedia)
Requirement already satisfied (use --upgrade to upgrade): futures in /usr/local/lib/python3.3/dist-packages (from goslate)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python3.3/dist-packages/six-1.7.3-py3.3.egg (from wolframalpha)

**Comment by endofline** [comment]
I'm also speculating here, but have you tried using pip3 instead of pip?

**Comment by gurumadmat** [comment]
Yes, I tried both of them.

**Comment by endofline** [comment]
Can you describe your environment furter? Are you using virtualenv? What platform, distro, etc.. It appears to be that your running instance of python cannot see the installed modules.

**Comment by gurumadmat** [comment]
I am using Ubuntu 13.10 with  Python 3.4.2. no virtualenv.

**Comment by endofline** [comment]
try manually installing the libraries with syntax `sudo pip3 install wikipedia`, etc (but run the bot as your local user)

**Comment by jfx41** [comment]
I got the same error when I enabled the syncrooms_autotranslate plugin:

*2015-04-09 21:59:06,284 - root - INFO - _load_hooks(): 1 hook(s) loaded
2015-04-09 21:59:06,289 - root - INFO - _start_sinks(): 2 sink thread(s) started
2015-04-09 21:59:08,657 - root - ERROR - No module named 'goslate' @ plugins.syncrooms_autotranslate
Traceback (most recent call last):
  File "./hangupsbot/hangupsbot.py", line 412, in _load_plugins
    exec("import {}".format(module_path))
  File "<string>", line 1, in <module>
  File "/home/kuzuri/Repos/hangupsbot/hangupsbot/plugins/syncrooms_autotranslate.py", line 2, in <module>
    import goslate
ImportError: No module named 'goslate'*

---------------

This fixed it for me (I'm using venvs) : *<b>$ pip3 install goslate</b>*
If you aren't using venvs you'll probably need to *<b>$ sudo pip3 install goslate</b>*

After that the plugin ran fine for me with no more errors.  Maybe the requirements did not get fully installed?  I would run pip3 install for each of those modules that it says it can't find.  Hopefully, that'll clear your errors up.

**Comment by j16sdiz** [comment]
Your `pip3` is trying to install to `/usr/local/python3`. This is not system default python.
Chance you are using different installation of python for pip and hangupsbot.
You may try `which pip3` and `which python3` to check the path, or `/usr/local/python3/bin/python hangupsbot.py` to force it use the custom installed instance.

**Comment by gurumadmat** [comment]
I did, everytime it says requirements are met. 
And he doesn't find pushbullet module.

**Comment by gurumadmat** [comment]
I'll try this. Thanks for the help 😃

**Comment by gurumadmat** [comment]
Sudo pip3.4 install goslate wikipedia wolframalpha
sudo pip3.4 install pushbullet.py

this did it for me.
thanks for the help guys!
