### ISSUE TITLE
Enhance the simpledemo websink to support image 

### ISSUE THREAD

**Issue by j16sdiz** [nylonee/hangupsbot#153]
Enhance the simpledemo websink to support image.
I guess the string can be a base64 string in the json.

**Comment by Riptides** [comment]
This is what you were talking about before (http://pastebin.com/HdGtvdHA) correct?

**Comment by endofline** [comment]
if somebody can get this tested earlier, can issue a PR into staging :)

**Comment by endofline** [comment]
rewrote the example and made it into a new standardised example for sinks that also support image uploads

**Comment by endofline** [comment]
improved sink reuse with a base class for generic sinks in 37b4ef90ee789a6b57eb6504e629541d82ca3a6c - backward compatibility with original sinks maintained

**Comment by endofline** [comment]
wiki documentation: https://github.com/nylonee/hangupsbot/wiki/Sinks-(2.4-and-above)
