### ISSUE TITLE
Plugin DnD Timer not working

### ISSUE THREAD

**Issue by Deuteu** [nylonee/hangupsbot#154]
The timer on the plugin DnD doesn't seems to work.

I tried several test :
/bot dnd 0
/bot dnd 1
/bot dnd (with default timer set to 6)

After the delay of the timer I'm still on DnD and it's confirmed by the /bot dnd that toggle to OFF the dnd-status.

**Comment by Deuteu** [comment]
https://github.com/nylonee/hangupsbot/blob/master/hangupsbot/plugins/dnd.py#L61
Maybe change 86400 by seconds_to_expire.
Can't test it yet (at work) but I think it should solved it cause seconds_to_expire doesn't seem to be used and expiry is set to 24h.

**Comment by endofline** [comment]
Thanks for the feedback @Deuteu - just tested this also with an hour timeout and found out its not expiring. Will be fixing this in an upcoming commit :)
