### ISSUE TITLE
Leaving (definitely) once you've said hi

### ISSUE THREAD

**Issue by djizus** [nylonee/hangupsbot#161]
Hello,
Is it possible to add an option to leave the bot once you've said Hi ? 
The DND function is great, but if I go on holidays (more than 3 days, which seems to be the cap for the DND), I'd like to be able to disable definitely the notifications.
For example, we could say good bye to the bot and be removed, until we say Hi again.
Thanks!

**Comment by endofline** [comment]
You can issue a `/bot optout` command in a private message with the bot. The opt-out is indefinite and will last until you manually toggle it off by calling `/bot optout` again. When opted-out, you will receive no private messages whatsoever from the bot.

**Comment by djizus** [comment]
Thanks ! Didnt know that :)
