### ISSUE TITLE
"Be more specific" feature is useless

### ISSUE THREAD

**Issue by nimbusparis** [nylonee/hangupsbot#172]
When tag people in a channel, as "@Eric" if there are many "Eric" in the channel, the bot will complain to be more specific. That would be great if it works.
If the choices are "Eric L" and "Eric M", if you specify "Eric L" for instance, the bot doesn't understand that you anticipated the message and complain to me more specific... The key is the space that seems to fool the bot.

**Comment by FrNico** [comment]
If you do @EricL (no space) it will work fine.

**Comment by nylonee** [comment]
The function will not work with spaces in the name, so '@EricL' and '@Eric_L' will both work, but not '@Eric L'.
