### ISSUE TITLE
autoreply plugin: per conv_id config

### ISSUE THREAD

**Issue by FrNico** [nylonee/hangupsbot#173]
Would it be possible in addition to a "global config" to have a per conv_id config for autoreplies?

Also, "autoreplies_enabled": false mentionned in config under "conversations" settings doesn't seem to do anything, I searched everywhere, I don't see a check on that actually :)

**Comment by nylonee** [comment]
Wow, not sure how we missed the 'autoreplies_enabled' config. Nice spotting!

Autoreplies already has the ability to run on a per conv_id basis. The syntax in the config.json would be:
```
"autoreplies": [
  "hello global",
  "Hello world!"
],
"conversations": {
  "CONV2_ID": {
    "autoreplies_enabled": false,
    "autoreplies": [
      "hello chat",
      "Hello world!"
    ]
  }
}
```
If any autoreplies exist for that conversation, then the bot will load up all of those conversation's autoreplies, ignoring the global list. If none exist for that conversation, then the bot will load up the global list.
