### ISSUE TITLE
root - ERROR - unrecoverable low-level error

### ISSUE THREAD

**Issue by notjasonmorris** [nylonee/hangupsbot#176]
I notice the bot runs for a a couple of days to a week then dies. Here's what I was able to see from the hangupsbot.log Let me know if you need more info.

http://pastebin.com/tswgGSi9

**Comment by nylonee** [comment]
It looks like the error is ServerDisconnectedError. While I'll look into it, a solution would be to use a bash pseudo-daemon to restart the bot when it goes down.

Please read #69

**Comment by nylonee** [comment]
Closing this as introducing a daemon is part of the plan for a future release
