### ISSUE TITLE
Allow certain keywords set by user to trigger mentions

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#25]
eg I want to be pinged everytime somebody says 'Nihal is awesome' in one of the groups that I'm in

**Comment by endofline** [comment]
as was previously suggested,.something like `/bot subscribe <word>` would be good.  issues/questions:
* phrase support
* tracking whether the user who subscribed to a word/phrase is actually in the hangout where the word/phrase was used - also a security/confidentiality issue

**Comment by nylonee** [comment]
`/bot subscribe <phrase>` and `/bot unsubscribe <phrase>` have been implemented. Phrases can be multiple words or single keyword, when you subscribe the bot will print all keywords that you have subscribed to.

Once a keyword has been subscribed to, for every message, it will go through the list of users in the chat/syncout, trying to find a matching user. If so, it will try to find a matching keyword of that user.

If all goes well, it'll then attempt to do a 1-1 ping to the user (pushbullet API also implemented). If 1-1 fails the failed attempt will be logged.

No time-based subscription implemented, no minimum/maximum phrase length implemented
