### ISSUE TITLE
Bot listening to commands from other HOs

### ISSUE THREAD

**Issue by zedixns** [nylonee/hangupsbot#27]
So don't know if it is normal or not, but seeing that the bot is in another HO is it normal for the bot to listen to them as well ? Or should it be limited to listen to only specific HOs?

Example: I sorta wanted to point out to whom am I written a response to in one hangout and because @David is a really common name, I received a private message from the bot that there are multiple Davids. OK. But should it work in other HOs

**Comment by nylonee** [comment]
@zedixns The names that you will receive in a private message are from people who are in the same Hangout/Syncout as where you made the mention. You will not be able to mention somebody who is not in the chat.

That being said, the bot does keep track of all users in all the conversations that it's in. You can [modify the config.json for mentions settings](https://github.com/nylonee/hangupsbot#mentions), and even configure this on a [per-conversation setting](https://github.com/nylonee/hangupsbot#admins-configuration) (which will always override the global setting).
