### ISSUE TITLE
When a person is in several chats of the same syncout, mentions do not work

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#28]

**Comment by endofline** [comment]
Check the log with -d, it shows the sequence of the mention and why it
fails.

**Comment by nylonee** [comment]
I believe the bug is because currently users in other syncouts get added
onto the list of users in a chat. This means that if the user is now in two
different chats, they get appended onto the list twice, and the bot detects
a duplicate, in which case it won't send a message.
