### ISSUE TITLE
[feature] allow comments in config.json

### ISSUE THREAD

**Issue by endofline** [nylonee/hangupsbot#36]
https://commentjson.readthedocs.org/en/latest/ seems like a likely candidate library that doesn't seem to break backward compatibility with config.py

**Comment by endofline** [comment]
this feature is also useful for plugin devs since config.json is shared to plugins via the `bot` object

**Comment by endofline** [comment]
This is a harder problem than expected as some plugins, commands may actually write to the configuration file on the fly, thus erasing any previous comments. Resolving this might require changing the original hangouts bot convention of using config.json and migrating affected keys to memory.json which isn't meant to be human-readable.

**Comment by endofline** [comment]
Current suggestion:
* Obsolete `/bot config`
* Migrate any dynamically-writable keys from `config.json` to `memory.json` (such as the keys used by `/bot dnd`)

**Comment by endofline** [comment]
This discussion may be relevant for you guys as well: @nylonee and @j16sdiz

**Comment by nylonee** [comment]
Moved this off the milestone. While it's a good idea to get this implemented, there are too many potentially bot-breaking things happening in here that we should hold it until we get our current staging pushed to master.

Would like to hear thoughts from others about obsoleting `/bot config`. It's a bit clunky, but a powerful command for interacting with bot settings.

**Comment by endofline** [comment]
change to `/bot memory` and have it modify `memory.json` instead

**Comment by endofline** [comment]
the big question: configure from bot (and allow writable config.json)? OR read-only config.json, but with comments?

...or potentially something else? 

@nylonee, comments invited, as well as anybody else :smiley:

**Comment by nylonee** [comment]
With the added [milestone](https://github.com/nylonee/hangupsbot/milestones/Fully%20configurable%20via%20Hangouts) to make the bot fully configurable via Hangouts, would a commented config.json still be needed?

**Comment by nylonee** [comment]
I'm making a decision here to stick with config.json (therefore uncommented), with the hopes of being able to push all configuration into the hangouts client, since that is where most of the interaction with the bot will happen anyway. This allows for non-programmers to be able to customize the bot too, and reduces the amount of time required to get a bot up and running out of the box.

I'll leave this open for a bit for more discussion, but that's the likely direction that we'll be going.

**Comment by endofline** [comment]
since the general direction appears to having config.json remain a directly-writeable file, i'll close this as wontfix, or more aptly *wontdo* :smile:
