### ISSUE TITLE
autoreplies should be a plugin (that supports UTF-8)

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#45]
The current configuration of autoreplies should be moved to the `/plugins` folder, to allow for more flexibility in developing that module. For example, current configuration [doesn't work with utf-8 formatting](https://github.com/nylonee/hangupsbot/issues/20#issuecomment-71972690)

**Comment by endofline** [comment]
python3 handles encoding differently, you may need to consider using encode/decode - perhaps any read from config.json needs to be re-encoded into unicode? references: https://docs.python.org/3/howto/unicode.html and http://stackoverflow.com/questions/4987327/how-do-i-check-if-a-string-is-unicode-or-ascii

**Comment by endofline** [comment]
verified working with chinese traditional 農曆新年 and chinese simplified 农历新年
