### ISSUE TITLE
Doumentation for plugins should move from README -> Wiki

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#46]
As the list of plugins begin to grow, it would be wise to move the documentation of how plugins work and the relevant commands and configs for them off the README and into the Wiki.

**Comment by endofline** [comment]
https://github.com/nylonee/hangupsbot/wiki/Plugin-Authoring

**Comment by endofline** [comment]
some of the base documentation will be left in the README for quick reference by admins and users - developer documentation has been moved

**Comment by nylonee** [comment]
Do we need to refine the wiki further at this point?

**Comment by endofline** [comment]
all plugin details have been moved to the wiki - start from the [list of plugins](https://github.com/nylonee/hangupsbot/wiki/Plugin-List)
