### ISSUE TITLE
send_html_to_conversation(id, html), send_html_to_user(id, html)

### ISSUE THREAD

**Issue by endofline** [nylonee/hangupsbot#54]
two unambiguous functions are required for future extension development:
* `send_html_to_conversation(id, html)`
* `send_html_to_user(id, html)`

optional new function: `send_html_to(user_or_conversation_id, html)` that utilises both functions

deprecated functions, maintained for legacy support:
* external_send_message()
* external_send_message_parsed()

**Comment by nylonee** [comment]
Definitely a good idea. You're right about adding features into a low-level command

**Comment by nylonee** [comment]
I've added a `send_html_to_user_or_conversation()`, but I think it's not working (unable to do extensive tests due to limited debugging messages). Will check up on this again in the morning.
