### ISSUE TITLE
Syncroom config.json migration

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#56]
Need to set up migration of the syncroom config from the two previous methods that are now deprecated.

**Comment by endofline** [comment]
this is a breaking change, it should have been in its own branch - is there any documentation for this?

**Comment by endofline** [comment]
findings so far: the "sending" handler is confirmed broken, but appears working because its relying on an older config structure

**Comment by endofline** [comment]
for reference, the new format in `config.json` is:
```  
"sync_rooms":
[
    [
        "CONV_ID_1",
        "CONV_ID_2"
    ],
    [
        "CONV_ID_3",
        "CONV_ID_4",
        "CONV_ID_5"
    ]
]
```

**Comment by endofline** [comment]
configuration migration applied and tested in staging
