### ISSUE TITLE
[feature] add translation support

### ISSUE THREAD

**Issue by pejotigrek** [nylonee/hangupsbot#57]
translation support for all strings would be nice - also something like aliases for bot's functions. all configured in json or any other file

**Comment by endofline** [comment]
This is a good idea, but there are several things that need to be added first:
* localisation file
* support for command aliases - this is a big one, the CommandDispatcher uses the function names from manual/auto introspection of the plugin files, so it means upgrading the plugin framework again to support command aliases

There is no timeframe I can ascertain to, but perhaps within the next major version upgrade - after all the outstanding bugs with current plugins are resolved.

**Comment by pejotigrek** [comment]
glad to hear!

btw command aliases - I came up with that idea while translating some strings for my local version - there were bot commands [started with /bot] represented by function names, and also triggers [started with /me], as I understand - recognized by strings entered by user. maybe aliases could work like the triggers? wouldn't that be easier to add?

**Comment by endofline** [comment]
You could possibly write a command remapping plugin that contains a lookup from `translated command` to `standard command` - then add a handler to listen for `/bot <translated command>` only. When these translated commands are received, the handler code would `yield from command.run(bot, event, *["<standard command>"])` accordingly.

Have look at https://github.com/nylonee/hangupsbot/wiki/Authoring-Bot-Extensions to see some examples and references for authoring a plugin.

**Comment by nylonee** [comment]
Worth noting that xmikos/hangupsbot now has [gettext support](https://github.com/xmikos/hangupsbot/commit/31f4e60929c7b6f4515f97723ccb1b8fdb872ef7) which I will work on merging into nylonee/hangupsbot now.

**Comment by nylonee** [comment]
Closing this now that 2.3.2 has gettext support
