### ISSUE TITLE
/me trigger doesn't work correctly from mobile client?

### ISSUE THREAD

**Issue by pejotigrek** [nylonee/hangupsbot#60]
desktop - web client 
after entering: _/me says something_
I can see in the hangouts window: **My_nick says something**

mobile client:
after entering: _/me says something_
I can see: **/me says something**

is it code-related or server-side issue?

**Comment by endofline** [comment]
This is a Hangouts client issue, exactly as you describe - /me only shows up with a nickname on desktop. Perhaps Google has separate development teams for mobile/desktop clients. It does not affect the bot operation in any way.
