### ISSUE TITLE
auto-expire DND (do not disturb) i.e. give it a snooze 

### ISSUE THREAD

**Issue by endofline** [nylonee/hangupsbot#61]
example usage:
```
/bot dnd <duration>
```
where `<duration>` = `<integer><m|h|d>` and not exceed 3 days

**Comment by nylonee** [comment]
Could we just simply things and have it as a `/bot dnd <hours>` which does not exceed 72 hours?
Also, how would we program this? I'm imagining we'd have to attach a timestamp to every dnd, and upon calling the dnd check for expired timestamps (and remove them).

**Comment by endofline** [comment]
yup and it's easier now because it all goes back to the same refactored function `_user_has_dnd()`

**Comment by endofline** [comment]
DND needs to be split into its own plugin since it's functionality is shared by both subscribe and mentions (and possibly future plugins)
