### ISSUE TITLE
restrictedadd will not force bot to leave upon creation of a group hangout with the bot

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#71]
I assume this is because there is no `hangups.MembershipChangeType.JOIN` that is triggered upon creation of a new hangout.

**Comment by endofline** [comment]
your assumption is correct - there does not seem to be an event observed - a possible workaround is a  periodic scan for existing users in a hangout and leaving when no admins/botkeepers are found

**Comment by nylonee** [comment]
That would have the side effect of impacting hangouts that were created by
admin and then the admin left (for whatever reason). A potential workaround
to that is to only do the scan for new hangouts that aren't previously
documented by the bot.

Another possible workaround could be to scan for hangout groups that only
have one message (ie. Just freshly created). Might be less data heavy, we
could call the scan like above, when the bot detects a new hangout that
hasn't been previously documented.

**Comment by endofline** [comment]
to account for the former (admins having left the HOs where they added the bot), the strict verify botkeeper check will be shipped switched off (and can be turned on with a config setting)

for the latter, i implemented a per-hangout `last_verified` flag  that only checks per message with a "throttle" of 60 seconds per verification

**Comment by endofline** [comment]
issue left for manual close, since it needs further verification

**Comment by nylonee** [comment]
Been working flawlessly for me for a while. Manually closing
