### ISSUE TITLE
Ability to make syncouts from hangouts

### ISSUE THREAD

**Issue by nylonee** [nylonee/hangupsbot#72]
It would be awesome if syncouts can be made by hangouts.
Some thoughts:
`/bot syncout <arraynumber>` would add the current chat to a syncout of that array number.
Since syncouts are stored in an array, this would be easy to implement. The hard bit is working out which array to add the syncout to. Maybe calling `/bot syncout` with no parameters specified will output the current syncout settings and attached hangouts, if any?

**Comment by endofline** [comment]
i would say `/bot attachsyncout <conversation_id>` where `conversation_id` is any matching conversation in an existing syncout configuration, and its counterpart `/bot detachsyncout` - command verbosity shouldn't be an issue since this is an admin command

**Comment by j16sdiz** [comment]
Maybe we can give a name to individual syncout?

**Comment by endofline** [comment]
do not merge the pending PR yet, these commands have not been marked as admin commands
