### ISSUE TITLE
[upgrade] framework needs an "allmessages" handler

### ISSUE THREAD

**Issue by endofline** [nylonee/hangupsbot#81]
presently the "message" handler is insufficient for some plugin requirements 

example: the **subscribe** plugin needs to monitor bot messages as well, but the standard `message` handler will not actually pass messages sent by the bot itself

this needs to be rectified in a future framework upgrade

**Comment by nylonee** [comment]
Will this be addressed in the 2.4 framework upgrade? I'm starting to see plugins (such as the slack plugin) that would work much better with an "allmessages" handler

**Comment by endofline** [comment]
(highlight commit message) important: be very careful with this handler, incorrect usage may result in infinite loops since the bot can respond to its own messages indefinitely

**Comment by endofline** [comment]
documented here: https://github.com/nylonee/hangupsbot/wiki/Plugin-Authoring-(2.4-and-above)#registering-handlers
