### ISSUE TITLE
After last pull have error

### ISSUE THREAD

**Issue by sasha2002** [nylonee/hangupsbot#85]
Client unexpectedly disconnected:
Failed to get initialize chat value: 'ds:7'

**Comment by nylonee** [comment]
This is an issue with the original [hangups library](https://github.com/tdryer/hangups) (see hangups [issue #61](https://github.com/tdryer/hangups/issues/61))

I suggest you pull the latest hangups and compile from source. Instructions for doing so are [here](http://hangups.readthedocs.org/en/stable/installation.html#install-from-source)

**Comment by sasha2002** [comment]
Yeah after install latest hangups library from sources all works.
